name: Sync to Bitbucket
on:
  push:
    paths:
      - 'src/tokens/**.json'
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        - name: Configure Git
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

        - name: Sync to Bitbucket
          env: 
            BITBUCKET_REPO: ${{ secrets.BITBUCKET_REPO_URL }}
            BITBUCKET_CRED: ${{ secrets.BITBUCKET_CREDENTIALS }}
          run: |
            git remote add bitbucket https://${BITBUCKET_CRED}@${BITBUCKET_REPO}
            git pull bitbucket master --rebase -q || echo "No existing branch, proceeding..."
            git add src/tokens
            git commit -m "[sync]: Sync from GitHub: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
            git push bitbucket master -q