name: Sync to Bitbucket
on:
  push:
    paths:
      - 'src/tokens/**.json'
  workflow_dispatch:  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Bitbucket sync directory
        run: |
          mkdir -p bitbucket-sync
      - name: clone repo
        env: 
          BITBUCKET_REPO: ${{ secrets.BITBUCKET_REPO_URL }}
          BITBUCKET_CRED: ${{ secrets.BITBUCKET_CREDENTIALS }}
        run: |
          cd bitbucket-sync
          if [ -d .git ]; then
            git pull
          else
            git clone https://${BITBUCKET_CRED}@${BITBUCKET_REPO} bitbucket-sync
          fi
      - name: Copy files
        run: |
          rm -rf bitbucket-sync/src/tokens
          mkdir -p bitbucket-sync/src
          cp -r src/tokens bitbucket-sync/src/tokens
      - name: Sync to Bitbucket
        env: 
          BITBUCKET_REPO: ${{ secrets.BITBUCKET_REPO_URL }}
          BITBUCKET_CRED: ${{ secrets.BITBUCKET_CREDENTIALS }}
        run: |
          cd bitbucket-sync
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "feat: sync from GitHub: $(git log -1 --pretty=format:%H) at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push origin master
            echo "Successfully synced to Bitbucket"
          else
            echo "No changes to sync"
          fi